services:
    duckdns:
        image: lscr.io/linuxserver/duckdns:latest
        container_name: duckdns
        environment:
            - SUBDOMAINS=hcg-leo
            - TOKEN=${TOKEN}
        volumes:
            - /home/hcg_leo/fedora-server/duckdns/config:/config
        restart: unless-stopped
